apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://127.0.0.1:6500
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJSXRRWEFZc3A1TG93Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemt3TlRNNE16QTBNQjRYRFRJMk1Ea3lOekU1TkRVd05Gb1hEVEkzTURreQpOekU1TkRVd05Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJEUjJQZEdYT1dHS09DMk0Ka0JJVzkrQTdOQkV0Vk5HS2M3Ryt4UnlqZnVUSlBYRERZdEZnUHh6ZWRDM0Zta081L1Bjbm1MYy90Nms1VFlzVQpwQUVQZDNLalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUTZBZDlhWlhHeFdGQTlBTWJhTW9XOVJzTWZWREFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlBd09ENStqQTRDZE54QUZKcjA1QnFXSWRPR2M1MGlLeXE2bEc2VXUxQkpKQUloQU84S21LN0IwRjNOajFYVwpFV1ZwN3gvZkhqVDV3V3p6ajRjaHlrNjNldWQvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzT1RBMU16Z3pNRFF3SGhjTk1qWXdPVEkzTVRrME5UQTBXaGNOTXpZd09USTBNVGswTlRBMApXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzT1RBMU16Z3pNRFF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRSzBraFVXeEg2T3dRcndmZEdvT2FOZGh4MlE4Kyttc3pzYkJJVVNXbGwKSUsxSHBwUWR4ZWtCbE9SUVBCbEFaT2grTGJwb3A1SzBNY3JEMTVpR09xdFlvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVU9nSGZXbVZ4c1ZoUVBRREcyaktGCnZVYkRIMVF3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQVBTZ3NGQld6ci9xRnBEVzhBcjEweU05bXMwTHh6Y0oKcTF1VGxqSUovS3Y5QWlFQTNPMFQwL3BzTHdFR3dnakMxa2I2dmJ6dXA4ZEpnNFpJbkdXSkpjbURPeG89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUplRHU2dlhVc1ZNN3BseURkTlNoZER4a1FVNlRuVnlYTzgwKzhhYlMrUU9vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFTkhZOTBaYzVZWW80TFl5UUVoYjM0RHMwRVMxVTBZcHpzYjdGSEtOKzVNazljTU5pMFdBLwpITjUwTGNXYVE3bjg5eWVZdHorM3FUbE5peFNrQVE5M2NnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
