apiVersion: v1
kind: ConfigMap
metadata:
  name: lomax-config
  labels:
    app: lomax
data:
  DB_HOST: "172.17.0.2"
  DB_PORT: "7001"
  DB_NAME: "lomax"
  AWS_ENDPOINT_URL: "http://172.17.0.2:4566"
  AWS_DEFAULT_REGION: "us-east-1"
  DYNAMODB_TABLE: "producto_atributos"
  ORIGINAL_BUCKET: "lomax-originales"
  THUMBNAIL_BUCKET: "lomax-miniaturas"
  LAMBDA_FUNCTION: "lomax-image-processor"
