apiVersion: v1
kind: Secret
metadata:
  name: lomax-secret
  labels:
    app: lomax
type: Opaque
stringData:
  DB_USER: "admin"
  DB_PASSWORD: "LomaxDB2026!"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
